In [34]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

In [35]:
data = np.array([[0, 0, 0], 
                 [0, 1, 1], 
                 [1, 0, 1], 
                 [1, 1, 1]])

In [36]:
print(data)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [37]:
X = data[:, :-1]
Y = data[:, -1]
print(X)
print()
print(Y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]

[0 1 1 1]


In [38]:
X.shape

(4, 2)

In [39]:
for b in range(X.shape[1] + 1):
    Y_pred_train = []
    accurate_rows = 0

    for x, y in zip(X, Y):
        y_pred = (np.sum(x) >= b)
        Y_pred_train.append(y_pred)
        accurate_rows += (y == y_pred)

    print(b, accurate_rows/X.shape[0])  

0 0.75
1 1.0
2 0.5


In [40]:
X_test = np.array([[0, 1], 
                  [1, 0], 
                  [0, 0]])

Y_test = np.array([1, 1, 0])

In [41]:
b = 1

Y_pred_test = []

for x in X_test:
    y_pred = (np.sum(x) >= b)
    Y_pred_test.append(y_pred)
    print(x, ' -> ', int(y_pred))

accuracy = accuracy_score(Y_pred_test, Y_test)
print('Accuracy: ', accuracy)  

[0 1]  ->  1
[1 0]  ->  1
[0 0]  ->  0
Accuracy:  1.0
